language: node_js
node_js:
- '7'
- '6'
cache: yarn
notifications:
  slack:
    secure: IYEQIV9B3bxpM0sanUE4CoFcYCt/rlGgS/e21kgfHv1bPryJabORQScsNqmOIJukBYUZcTHFIEEQqUP403vgdcyRwvYFJapLPUpbr1YYa7aUs4D7fDpfBr8R6uAAmQ188TTsfW8Wk2OYPEe7V1FQjlDdGXm7BYC3IwfdWmeaYlL9tfG33b2vuG/iwz5pYWrF2IwLsY1DzGKT8KeoYj3/4V+jBnBZEfX7R4NEcLh4leIRpPqnXtvDZ7E5hqhm6Z2uTJK6njrK8rEo6b7hOYixMKCRUUoo3A1THNxrkxH4L7TEtNQ2cqSj+89ZZDJzVciYyXurBzSyWdgut0iTpJriAT3vDf/PWCnV2CA3qxU4moFVWQRXxmgmQ6W+HKxINKimmCVuSPOunaaJJBntAa9XCGChKPkRDjGaQEoe2G4Z1HTajNwCbBEk4hU0GgdNwAFQQDpaNv4G1H4Mj7VKNA5W3Fov10ZT/UzRjjU2VKwFsz/AensP/IK/l5/hQNyVriQb6lev5WwzxscOy2CN+b6OpoKEAB8Bs4V4QeMMwK0W8hKYndc9XZ4PkLIcOVi4A8cjT/hQ+4SKkNQFitwc7qSxAYQm+iClc+8Uiuh2LIRM2km+kWQpKRWV0frSk9A38xsyPBAPMVd6RUZkHNWeKxotYiby6RI4Oidmbr4OTbl3A8M=
